### ISSUE TITLE
Предложение: тесты по модулям

### ISSUE THREAD

**Issue by dhvcc** [vkbottle/vkbottle#344]
На данный момент тесты только в корне

Я предлагаю тесты переносить в соответствующие им модули. Нам нужно тестировать не только конструкции и их работу, а и основные куски кода (не только `ABCView`, но и `MessageView`)
Не совсем удобно, когда все тесты в корне. Можно оставить там фикстуры и базовые тесты

**Так тесты не будут попадать в билд** ([референс](https://python-poetry.org/docs/pyproject/#include-and-exclude)):
`pyproject.toml`
```toml
[tool.poetry]
exclude = ["vkbottle/**/tests/*"]
# ...
```
